### PR TITLE
Reflect cypress 10 changes for getTotalSpecs

### LINKED ISSUE #116: Error thrown when spec finishes for new Cypress 10
I'm getting this error right then the first spec finishes for Cypress Version 10.0.3

```
Channel closed
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at new NodeError (node:internal/errors:371:5)
    at ChildProcess.target.send (node:internal/child_process:721:16)
    at Runner.<anonymous> (/e2e/node_modules/@reportportal/agent-js-cypress/lib/cypressReporter.js:115:21)
    at Runner.emit (node:events:402:35)
    at Runner.emit (node:domain:475:12)
    at Reporter.emit (/root/.cache/Cypress/10.0.3/Cypress/resources/app/packages/server/lib/reporter.js:362:46)
    at Object.onMocha (/root/.cache/Cypress/10.0.3/Cypress/resources/app/packages/server/lib/project-base.js:283:34)
    at Socket.<anonymous> (/root/.cache/Cypress/10.0.3/Cypress/resources/app/packages/server/lib/socket-base.js:250:40)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at Socket.emitUntyped (/root/.cache/Cypress/10.0.3/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/typed-events.js:69:22)
    at /root/.cache/Cypress/10.0.3/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

### PR DESCRIPTION
**Pull request by orgads**
Fixes #116.

Reviving #123

### CODE REVIEW

**Comment by orgads** [comment]
ping

**Comment by orgads** [comment]
@AmsterGet?

**Comment by orgads** [comment]
Confirmed it fixes the issue.

**Comment by AmsterGet** [comment]
Hello @orgads !
I'm currently on vacation and plan to finish the review and publish your changes after Thursday this week.
Sorry for the delay in replies.

**Comment by orgads** [comment]
Thank you very much.

**Comment by orgads** [comment]
Hi. Kind reminder :)

**Comment by AmsterGet** [comment]
@orgads don't worry, I'm in progress with it.

**Review by AmsterGet — APPROVED** [review]

**Comment by AmsterGet** [comment]
Thank you very much @orgads !
It will go to 5.0.5.
ETA - upcoming sprint (current week/beginning of the next week).

**Comment by orgads** [comment]
Thank you.

**Pull request merged**
